version: '3.1'
services:
  webserver:
    image: myhouse_flask
    ports:
      - "5000:5000"
    secrets:
      - flask_key
      - web_login_password
      - redis_password
  redis:
    image: myhouse_redis
    ports:
      - "6379:6379"
    secrets:
      - redis_password
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf.orig:ro
  pushover:
    image: myhouse_pushover
    volumes:
      - ./common:/app/common:ro
    secrets:
      - redis_password
      - pushover_keys
  wlan_presence:
    image: myhouse_wlan_presence
    volumes:
      - ./common:/app/common:ro
    secrets:
      - redis_password
      - wlan_router
    deploy:
      restart_policy:
        condition: none
secrets:
  flask_key:
    file: ./secret/flask_key
  web_login_password:
    file: ./secret/web_login_password
  redis_password:
    file: ./secret/redis_password
  pushover_keys:
    file: ./secret/pushover_keys
  wlan_router:
    file: ./secret/wlan_router
