version: '3.1'
services:
  profiles:
    image: flask_web
    ports:
      - "5000:5000"
    secrets:
      - flask_key
      - login_password
secrets:
  flask_key:
    file: ./passwords/flask.txt
  login_password:
    file: ./passwords/login.txt
