version: '3.1'
services:
  profiles:
    image: flask_web
    ports:
      - "5000:5000"
    secrets:
      - flask_key
      - web_login_password
      - redis_password
secrets:
  flask_key:
    file: ./secret/flask_key
  web_login_password:
    file: ./secret/web_login_password
  redis_password:
    file: ./secret/redis_password
